; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -mtriple=tinygpu -verify-machineinstrs < %s | FileCheck -check-prefix=ASM %s

define i8 @addi(i8 %a) {
; ASM-LABEL: addi:
; ASM:       # %bb.0:
; ASM-NEXT:    CONST R1, 1
; ASM-NEXT:    ADD R0, R0, R1
; ASM-NEXT:    RET
  %1 = add i8 %a, 1
  ret i8 %1
}
