; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -mtriple=tinygpu -verify-machineinstrs < %s | FileCheck -check-prefix=ASM %s

define i8 @brcompare(i8 %a, i8 %b) {
; ASM-LABEL: brcompare:
; ASM:       # %bb.0:
; ASM-NEXT:    CMP R0, R1
; ASM-NEXT:    BRnp .LBB0_2
; ASM-NEXT:    BRnzp .LBB0_1
; ASM-NEXT:  .LBB0_1: # %if
; ASM-NEXT:    CONST R0, 0
; ASM-NEXT:    RET
; ASM-NEXT:  .LBB0_2: # %else
; ASM-NEXT:    CONST R0, 1
; ASM-NEXT:    RET
  %1 = icmp eq i8 %a, %b
  br i1 %1, label %if, label %else

if:
  ret i8 0

else:
  ret i8 1
}
