; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -mtriple=tinygpu -verify-machineinstrs < %s | FileCheck -check-prefix=ASM %s

define i8 @const() {
; ASM-LABEL: const:
; ASM:       # %bb.0:
; ASM-NEXT:    CONST R0, 2
; ASM-NEXT:    RET
  ret i8 2
}
