; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -mtriple=tinygpu -verify-machineinstrs < %s | FileCheck -check-prefix=ASM %s

define void @intrinsic(ptr addrspace(1) %a) {
; ASM-LABEL: intrinsic:
; ASM:       # %bb.0:
; ASM-NEXT:    MUL R1, blockIdx, blockDim
; ASM-NEXT:    ADD R1, R1, threadIdx
; ASM-NEXT:    STR R1, R0
; ASM-NEXT:    RET
  %tid = call i8 @llvm.tinygpu.workitem.id.x()
  %bid = call i8 @llvm.tinygpu.workgroup.id.x()
  %bdim = call i8 @llvm.tinygpu.workgroup.size.x()
  %1 = mul i8 %bid, %bdim
  %2 = add i8 %1, %tid
  store i8 %2, ptr addrspace(1) %a, align 1
  ret void
}

declare i8 @llvm.tinygpu.workitem.id.x()
declare i8 @llvm.tinygpu.workgroup.id.x()
declare i8 @llvm.tinygpu.workgroup.size.x()
