; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -mtriple=tinygpu -verify-machineinstrs < %s | FileCheck -check-prefix=ASM %s

define void @intrinsic(ptr addrspace(1) %a) {
; ASM-LABEL: intrinsic:
; ASM:       # %bb.0:
; ASM-NEXT:    STR threadIdx, R0
; ASM-NEXT:    RET
  %tid = call i8 @llvm.tinygpu.workitem.id.x()
  store i8 %tid, ptr addrspace(1) %a, align 1
  ret void
}

declare i8 @llvm.tinygpu.workitem.id.x()
