; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -mtriple=tinygpu -verify-machineinstrs < %s | FileCheck -check-prefix=ASM %s

define i8 @ld(ptr %a) {
; ASM-LABEL: ld:
; ASM:       # %bb.0:
; ASM-NEXT:    LDR R11, R0
; ASM-NEXT:    RET
  %1 = load i8, ptr %a
  ret i8 %1
}
