; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -mtriple=tinygpu -verify-machineinstrs < %s | FileCheck -check-prefix=ASM %s

define i8 @muli(i8 %a) {
; ASM-LABEL: muli:
; ASM:       # %bb.0:
; ASM-NEXT:    CONST R4, 3
; ASM-NEXT:    MUL R11, R0, R4
; ASM-NEXT:    RET
  %1 = mul i8 %a, 3
  ret i8 %1
}
