; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -mtriple=tinygpu -verify-machineinstrs < %s | FileCheck -check-prefix=ASM %s

define i8 @sdivi(i8 %a) {
; ASM-LABEL: sdivi:
; ASM:       # %bb.0:
; ASM-NEXT:    CONST R4, 2
; ASM-NEXT:    DIV R11, R0, R4
; ASM-NEXT:    RET
  %1 = sdiv i8 %a, 2
  ret i8 %1
}
