; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -mtriple=tinygpu -verify-machineinstrs < %s | FileCheck -check-prefix=ASM %s

define i8 @sdivi1(i8 %a) {
; ASM-LABEL: sdivi1:
; ASM:       # %bb.0:
; ASM-NEXT:    RET
  %1 = sdiv i8 %a, 1
  ret i8 %1
}

define i8 @sdivi2(i8 %a) {
; ASM-LABEL: sdivi2:
; ASM:       # %bb.0:
; ASM-NEXT:    CONST R1, 2
; ASM-NEXT:    DIV R0, R0, R1
; ASM-NEXT:    RET
  %1 = sdiv i8 %a, 2
  ret i8 %1
}
