; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -mtriple=tinygpu -verify-machineinstrs < %s | FileCheck -check-prefix=ASM %s

define void @st(ptr %a, i8 %b) {
; ASM-LABEL: st:
; ASM:       # %bb.0:
; ASM-NEXT:    STR R1, R0
; ASM-NEXT:    RET
    store i8 %b, ptr %a, align 1
    ret void
}
