; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -mtriple=tinygpu -verify-machineinstrs < %s | FileCheck -check-prefix=ASM %s

define i8 @sub(i8 %a, i8 %b) {
; ASM-LABEL: sub:
; ASM:       # %bb.0:
; ASM-NEXT:    SUB R0, R0, R1
; ASM-NEXT:    RET
  %1 = sub i8 %a, %b
  ret i8 %1
}
